"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env (development)
# Why: keep secrets out of source code, and make config reproducible.
#
# This requires: pip install python-dotenv
# If not installed, Django will still run, but only OS env vars will work.
try:
    from dotenv import load_dotenv  # type: ignore

    load_dotenv(BASE_DIR / ".env")
except Exception:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-n1lnj9=g7%7t!+^%ad%7td$g@n-#asnlwnhk^__ns7m3rem$o6",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    'rest_framework_simplejwt',
    "accounts",
    "profiles",
    "blog",
    "ai",
]

REST_FRAMEWORK = {
    #默认使用JWT
    'DEFAULT_AUTHENTICATION_CLASSES': [
        #所有视图验证都需要token
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    #设置默认权限
    'DEFAULT_PERMISSION_CLASSES': [
        #登录读写，未登录只能读
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}


# Simple JWT 配置
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # access token 15分钟过期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),    # refresh token 7天过期
    'ROTATE_REFRESH_TOKENS': True,                  # 刷新后重新生成 refresh token
    'BLACKLIST_AFTER_ROTATION': True,                # 刷新后的旧 token 加入黑名单
    'ALGORITHM': 'HS256',                          # 使用 HS256 算法
    'SIGNING_KEY': SECRET_KEY,                      # 使用 Django SECRET_KEY 签名
    'AUTH_HEADER_TYPES': ('Bearer',),               # Authorization header 格式：Bearer <token>
}                                                   # Bearer 表示"持有者"，即持有此 token 的人就是本人

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 数据库链接配置表
DATABASES = {
    'default': {
        # 数据库类型
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DB_NAME", "aiblog"),
        'USER': os.getenv("DB_USER", "root"),
        'PASSWORD': os.getenv("DB_PASSWORD", ""),
        'HOST': os.getenv("DB_HOST", "127.0.0.1"),
        'PORT': os.getenv("DB_PORT", "3306"),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (用户上传的文件)
MEDIA_URL = 'media/'  # 访问上传文件的 URL 前缀
MEDIA_ROOT = BASE_DIR / 'media'  # 上传文件的存储路径


# AI配置
AI_API_KEY = os.getenv('AI_API_KEY', 'DASHSCOPE_API_KEY')
AI_BASE_URL = os.getenv('AI_BASE_URL', 'https://dashscope.aliyuncs.com/compatible-mode/v1')
AI_MODEL = os.getenv('AI_MODEL', 'qwen-turbo')
